# ADL2CSV
ADLtagger形式のディレクトリ構造からCSVデータを抜き出し, tag情報を付加したうえでひとつのCSVファイルにまとめて出力する.

### [注意!!] タイムスタンプの桁落ち 必ず3桁にしないとsortした時変になる.

In [1]:
import os # os.mkdir(path)でdirectoryを作成

import pandas as pd
import numpy as np
import xml.etree.ElementTree as ET
import datetime as dt

# Main関数
以下の２つのセルを実行

In [51]:
import os # os.mkdir(path)でdirectoryを作成

import pandas as pd
import numpy as np
import xml.etree.ElementTree as ET
import datetime as dt


class ADL2Csv(object):
    """
    Generate Labeled signal data
    """
    def __init__(self, path_to_xml, path_to_csv_root_dir='./data/fromADL/', path_to_output_dir='./data/LabeledCSV/', sensor_tag='None', fix_timestamp=False):
        """
        Argument
        --------
        path_to_xml: str(Labele data file generated by ADLtagger)
        path_to_log_dir: str(path to csv files[ADLtagger format])
        path_to_output_dir: str
        """
        self.path_to_xml = path_to_xml
        self.path_to_csv_root_dir = path_to_csv_root_dir
        self.path_to_output_dir = path_to_output_dir
        self.sensor_tag = sensor_tag
        self.fix_timestamp = fix_timestamp
        
        
    """Read Data"""
    def read_data(self):
        print("Step1: Read csv files and label xml data.")
        # CSV files
        df = pd.DataFrame()
        df = self.BFS(df, self.path_to_csv_root_dir)
        #  timestampの桁落ちを修正
        print("[Read Data] fix timestamp = ", self.fix_timestamp)
        if self.fix_timestamp:
            df_tmp = df[["time"]].copy()
            df_tmp["time_1"] = "none"
            df_tmp["time_2"] = "none"
            df_tmp[["time_1","time_2"]] = df_tmp["time"].str.split(".", expand=True)
            df["time"] = df_tmp["time_1"] + "." +df_tmp["time_2"].str.zfill(3)
        self.df = df.sort_values(by=["time"]).reset_index(drop=True)
        # Label
        self.df_label = self.get_labels()
        print(">> Success: df="+str(self.df.shape)+", df_label="+str(self.df_label.shape)+"\n")
        return self.df, self.df_label
        
    ## CSVファイルを取得 ##
    def BFS(self, df, current_path):
        # 現在のディレクトリにあるディレクトリを取得
        for x in os.listdir(current_path):
            print(">>",current_path+x)
            if os.path.isdir(current_path + x):
                # ディレクトリが存在する場合 ==> より深く潜る
                df = self.BFS(df, current_path + x + '/')
            elif os.path.isfile(current_path + x):
                # ファイル場合 ==> CSVか判定 ==> YES: dfに追加
                root, ext = os.path.splitext(x)
                if ext == ".csv":
                    df = pd.concat([df, pd.read_csv(current_path+x)])
        return df

    ## XMLの解析 ##
    def get_labels(self):
        def parse_time_str(s):
            try:
                ymd, HMS, ms = s[0:10].replace('-', ''), s[11:19], s[20:]
            except IndexError as e:
                ymd, HMS, ms = s[0:10].replace('-', ''), s[11:19], '000'
            return str(ymd)+'_'+str(HMS)+'.'+str(ms).ljust(3, '0')
        # XML
        tree = ET.parse(self.path_to_xml)
        elem = tree.getroot()
        df_label = []
        for e in elem.findall("labellist"):
            label = e.find("eventtype").text
            start = parse_time_str(e.find("start").text)
            end = parse_time_str(e.find("end").text)
            df_label.append([label, start, end])
        return pd.DataFrame(df_label, columns=["label", "start", "end"])

    
    
    """Add Labels"""
    def add_label(self):
        print("Step2: Add label to sensor data.")
        df, df_label =  self.df, self.df_label
        # timedelta型に変換
        df["time"] = pd.to_datetime(df["time"], format="%Y%m%d_%H:%M:%S.%f") 
        df_label["start"] = pd.to_datetime(df_label["start"], format="%Y%m%d_%H:%M:%S.%f")
        df_label["end"] = pd.to_datetime(df_label["end"], format="%Y%m%d_%H:%M:%S.%f")
        
        labels, label_ids = ["none" for i in range(len(df)) ], [-1 for i in range(len(df)) ]
        for i in range(len(df_label)):
            label, start, end = df_label.loc[i,"label"], df_label.loc[i,"start"], df_label.loc[i,"end"]
            index = df[(df["time"] >= start) & (df["time"] <= end)].index
            # label配列を修正
            for j in index:
                labels[j], label_ids[j] = label, i
            if i%50 == 0:
                print(">> id="+str(i).zfill(4)+": label=`"+label+"`,\t\tTime=[ "+str(start)+", "+str(end)+"]")
        df["label"], df["label_id"] = labels, label_ids 
        self.df = df
        print(">> Success: df.shape=", self.df.shape, "\n")
        return df


    """CSV書き出し"""
    def to_csv(self):
        print("Step3: Write CSV files.")
        # ディレクトリを作成
        df, df_label, output_path = self.df, self.df_label, self.path_to_output_dir
        if not os.path.isdir(output_path):
            os.mkdir(output_path)
        df.to_csv(output_path+self.sensor_tag+"_labeled.csv")
        print(">> Success: Write csv.[", output_path+self.sensor_tag+"_labeled.csv", "]")
        df_label.to_csv(output_path+"label.csv")
        print(">> Success: Write csv.[", output_path+"labele.csv", "]")
        df_label[["label", "start"]].groupby(by=["label"]).count().sort_values(["start"], ascending=False).to_csv(output_path+"label_counts.csv")
    
    
# converter = ADL2Csv(path_to_xml='./data/2017_09_21/03_fromADL/data.xml',
#                     path_to_csv_root_dir='./data/2017_09_21/03_fromADL/data/acc2/',
#                     path_to_output_dir='./data/2017_09_21/04_Labeled/',
#                    sensor_tag="acc")
# df, df_label = converter.read_data()
# df = converter.add_label()
# converter.to_csv()
# display(df.head(10))
#display(df_label.head(10))

In [52]:

root_dir = "/root/upconversion/data/2017_12_15/08_higashide"


converter = ADL2Csv(path_to_xml=root_dir+"/data.xml",
                    path_to_csv_root_dir=root_dir+"/data/acc2/",
                    path_to_output_dir='./data/2017_12_15/',
                   sensor_tag="acc",
                   fix_timestamp=True)
df, df_label = converter.read_data()
df = converter.add_label()
converter.to_csv()
display(df.head(10))

Step1: Read csv files and label xml data.
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_183100_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_182500_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_182200_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_183000_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_182400_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_184000_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_183600_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_183800_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_183200_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_181800_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_183500_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_182900_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_182800_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_182000_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_182600_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_183900_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_182100_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_181900_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_183400_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_182700_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_182300_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_183700_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_183300_acc2.csv
[BFS] fix timestamp =  True
>> Success: df=(1324650, 4), df_label=(116, 3)

Step2: Add label to sensor data.
>> id=0000: label=`start_gesture_session`,		Time=[ 2017-12-15 18:18:32.979000, 2017-12-15 18:18:34.737000]
>> id=0050: label=`pinch_out`,		Time=[ 2017-12-15 18:23:14.248000, 2017-12-15 18:23:14.626000]
>> id=0100: label=`drill`,		Time=[ 2017-12-15 18:37:22.621000, 2017-12-15 18:37:27.003000]
>> Success: df.shape= (1324650, 6)

Step3: Write CSV files.
>> Success: Write csv.[ ./data/2017_12_15/acc_labeled.csv ]
>> Success: Write csv.[ ./data/2017_12_15/labele.csv ]

                     time    x     y      z label  label_id
0 2017-12-15 18:18:27.731  116 -1038  10193  none        -1
1 2017-12-15 18:18:27.732   65 -1026  10208  none        -1
2 2017-12-15 18:18:27.733   14  -974  10242  none        -1
3 2017-12-15 18:18:27.734   -3  -972  10262  none        -1
4 2017-12-15 18:18:27.735   12  -991  10289  none        -1
5 2017-12-15 18:18:27.736   -1  -967  10245  none        -1
6 2017-12-15 18:18:27.737  -54  -935  10245  none        -1
7 2017-12-15 18:18:27.738  -89  -940  10286  none        -1
8 2017-12-15 18:18:27.739  -89  -996  10269  none        -1
9 2017-12-15 18:18:27.740  -71 -1028  10227  none        -1

In [55]:
""" 2017.12.15
"""
import pandas as pd


root_dir = "/root/upconversion/data/2017_12_15/"
sensor = "acc"
name_list = [
    "01_kawabe", "02_higashinaka", "03_yasuda", "04_kamiya",
    "05_ishiyama", "06_yoshimura", "07_aiko", "08_higashide",
]


for _name in name_list[:]:
    print(">> ", _name)
    root_dir = "/root/upconversion/data/2017_12_15/{}".format(_name)
    df_raw = pd.read_csv(root_dir+"/data/Labeled/{}_labeled.csv".format(sensor), index_col=0)
    
    converter = ADL2Csv(path_to_xml=root_dir+"/data.xml",
                        path_to_csv_root_dir=root_dir+"/data/acc2/",
                        path_to_output_dir=root_dir+"/data/Labeled/",
                        sensor_tag=sensor,
                        fix_timestamp=True)
    df, df_label = converter.read_data()
    df = converter.add_label()
    converter.to_csv()
    display(df.head(10))

>>  01_kawabe

/usr/local/lib/python3.5/dist-packages/numpy/lib/arraysetops.py:463: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

Step1: Read csv files and label xml data.
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_115700_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_120400_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_120100_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_121000_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_115800_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_120200_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_114700_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_120000_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_114800_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_121100_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_115900_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_120900_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_115600_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_115100_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_115400_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_120600_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_114900_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_115300_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_120800_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_120500_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_120300_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_115000_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_115200_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_115500_acc2.csv
>> /root/upconversion/data/2017_12_15/01_kawabe/data/acc2/acc2_R/20171215_120700_acc2.csv
[BFS] fix timestamp =  True
>> Success: df=(1434920, 4), df_label=(124, 3)

Step2: Add label to sensor data.
>> id=0000: label=`exclude`,		Time=[ 2017-12-15 11:47:47.541000, 2017-12-15 11:47:47.725000]
>> id=0050: label=`tap_arm`,		Time=[ 2017-12-15 11:54:01.498000, 2017-12-15 11:54:01.817000]
>> id=0100: label=`massarger_slow`,		Time=[ 2017-12-15 12:08:09.946000, 2017-12-15 12:08:11.542000]
>> Success: df.shape= (1434920, 6)

Step3: Write CSV files.
>> Success: Write csv.[ /root/upconversion/data/2017_12_15/01_kawabe/data/Labeled/acc_labeled.csv ]
>> Success: Write csv.[ /root/upconversion/data/2017_12_15/01_kawabe/data/Labeled/labele.csv ]

                     time     x   y      z label  label_id
0 2017-12-15 11:47:42.121  2152  38  10125  none        -1
1 2017-12-15 11:47:42.122  2174  67  10115  none        -1
2 2017-12-15 11:47:42.123  2198  72  10125  none        -1
3 2017-12-15 11:47:42.124  2169 -18  10125  none        -1
4 2017-12-15 11:47:42.125  2186 -38  10142  none        -1
5 2017-12-15 11:47:42.126  2176 -48  10144  none        -1
6 2017-12-15 11:47:42.127  2130 -35  10135  none        -1
7 2017-12-15 11:47:42.128  2132 -18  10186  none        -1
8 2017-12-15 11:47:42.129  2103 -28  10164  none        -1
9 2017-12-15 11:47:42.130  2066 -28  10135  none        -1

>>  02_higashinaka
Step1: Read csv files and label xml data.
>> /root/upconversion/data/2017_12_15/02_higashinaka/data/acc2/acc2_R
>> /root/upconversion/data/2017_12_15/02_higashinaka/data/acc2/acc2_R/20171215_134600_acc2.csv
>> /root/upconversion/data/2017_12_15/02_higashinaka/data/acc2/acc2_R/20171215_135000_acc2.csv
>> /root/upconversion/data/2017_12_15/02_higashinaka/data/acc2/acc2_R/20171215_134000_acc2.csv
>> /root/upconversion/data/2017_12_15/02_higashinaka/data/acc2/acc2_R/20171215_134700_acc2.csv
>> /root/upconversion/data/2017_12_15/02_higashinaka/data/acc2/acc2_R/20171215_134200_acc2.csv
>> /root/upconversion/data/2017_12_15/02_higashinaka/data/acc2/acc2_R/20171215_134800_acc2.csv
>> /root/upconversion/data/2017_12_15/02_higashinaka/data/acc2/acc2_R/20171215_135200_acc2.csv
>> /root/upconversion/data/2017_12_15/02_higashinaka/data/acc2/acc2_R/20171215_133800_acc2.csv
>> /root/upconversion/data/2017_12_15/02_higashinaka/data/acc2/acc2_R/20171215_133600_acc2.csv
>> /root/upconversion/data/2017_12_15/02_higashinaka/data/acc2/acc2_R/20171215_134400_acc2.csv
>> /root/upconversion/data/2017_12_15/02_higashinaka/data/acc2/acc2_R/20171215_134300_acc2.csv
>> /root/upconversion/data/2017_12_15/02_higashinaka/data/acc2/acc2_R/20171215_133900_acc2.csv
>> /root/upconversion/data/2017_12_15/02_higashinaka/data/acc2/acc2_R/20171215_133700_acc2.csv
>> /root/upconversion/data/2017_12_15/02_higashinaka/data/acc2/acc2_R/20171215_133300_acc2.csv
>> /root/upconversion/data/2017_12_15/02_higashinaka/data/acc2/acc2_R/20171215_134900_acc2.csv
>> /root/upconversion/data/2017_12_15/02_higashinaka/data/acc2/acc2_R/20171215_134100_acc2.csv
>> /root/upconversion/data/2017_12_15/02_higashinaka/data/acc2/acc2_R/20171215_133500_acc2.csv
>> /root/upconversion/data/2017_12_15/02_higashinaka/data/acc2/acc2_R/20171215_135100_acc2.csv
>> /root/upconversion/data/2017_12_15/02_higashinaka/data/acc2/acc2_R/20171215_133400_acc2.csv
>> /root/upconversion/data/2017_12_15/02_higashinaka/data/acc2/acc2_R/20171215_134500_acc2.csv
[BFS] fix timestamp =  True
>> Success: df=(1194383, 4), df_label=(121, 3)

Step2: Add label to sensor data.
>> id=0000: label=`start_gesture_session`,		Time=[ 2017-12-15 13:33:19.199000, 2017-12-15 13:33:24.606000]
>> id=0050: label=`flick_left`,		Time=[ 2017-12-15 13:37:37.318000, 2017-12-15 13:37:37.678000]
>> id=0100: label=`blender`,		Time=[ 2017-12-15 13:49:44.750000, 2017-12-15 13:49:46.541000]
>> Success: df.shape= (1194383, 6)

Step3: Write CSV files.
>> Success: Write csv.[ /root/upconversion/data/2017_12_15/02_higashinaka/data/Labeled/acc_labeled.csv ]
>> Success: Write csv.[ /root/upconversion/data/2017_12_15/02_higashinaka/data/Labeled/labele.csv ]

                     time     x     y     z label  label_id
0 2017-12-15 13:33:01.166 -2757  1139  9683  none        -1
1 2017-12-15 13:33:01.167 -2740  1176  9673  none        -1
2 2017-12-15 13:33:01.168 -2711  1273  9693  none        -1
3 2017-12-15 13:33:01.169 -2657  1371  9705  none        -1
4 2017-12-15 13:33:01.170 -2579  1405  9722  none        -1
5 2017-12-15 13:33:01.171 -2527  1447  9717  none        -1
6 2017-12-15 13:33:01.172 -2508  1461  9668  none        -1
7 2017-12-15 13:33:01.173 -2501  1422  9712  none        -1
8 2017-12-15 13:33:01.174 -2535  1378  9737  none        -1
9 2017-12-15 13:33:01.175 -2579  1320  9756  none        -1

>>  03_yasuda
Step1: Read csv files and label xml data.
>> /root/upconversion/data/2017_12_15/03_yasuda/data/acc2/acc2_R
>> /root/upconversion/data/2017_12_15/03_yasuda/data/acc2/acc2_R/20171215_141900_acc2.csv
>> /root/upconversion/data/2017_12_15/03_yasuda/data/acc2/acc2_R/20171215_142600_acc2.csv
>> /root/upconversion/data/2017_12_15/03_yasuda/data/acc2/acc2_R/20171215_141500_acc2.csv
>> /root/upconversion/data/2017_12_15/03_yasuda/data/acc2/acc2_R/20171215_142100_acc2.csv
>> /root/upconversion/data/2017_12_15/03_yasuda/data/acc2/acc2_R/20171215_142000_acc2.csv
>> /root/upconversion/data/2017_12_15/03_yasuda/data/acc2/acc2_R/20171215_141200_acc2.csv
>> /root/upconversion/data/2017_12_15/03_yasuda/data/acc2/acc2_R/20171215_141300_acc2.csv
>> /root/upconversion/data/2017_12_15/03_yasuda/data/acc2/acc2_R/20171215_142400_acc2.csv
>> /root/upconversion/data/2017_12_15/03_yasuda/data/acc2/acc2_R/20171215_142200_acc2.csv
>> /root/upconversion/data/2017_12_15/03_yasuda/data/acc2/acc2_R/20171215_142500_acc2.csv
>> /root/upconversion/data/2017_12_15/03_yasuda/data/acc2/acc2_R/20171215_142300_acc2.csv
>> /root/upconversion/data/2017_12_15/03_yasuda/data/acc2/acc2_R/20171215_141000_acc2.csv
>> /root/upconversion/data/2017_12_15/03_yasuda/data/acc2/acc2_R/20171215_140900_acc2.csv
>> /root/upconversion/data/2017_12_15/03_yasuda/data/acc2/acc2_R/20171215_141100_acc2.csv
>> /root/upconversion/data/2017_12_15/03_yasuda/data/acc2/acc2_R/20171215_141800_acc2.csv
>> /root/upconversion/data/2017_12_15/03_yasuda/data/acc2/acc2_R/20171215_141700_acc2.csv
>> /root/upconversion/data/2017_12_15/03_yasuda/data/acc2/acc2_R/20171215_141400_acc2.csv
>> /root/upconversion/data/2017_12_15/03_yasuda/data/acc2/acc2_R/20171215_141600_acc2.csv
[BFS] fix timestamp =  True
>> Success: df=(1011260, 4), df_label=(119, 3)

Step2: Add label to sensor data.
>> id=0000: label=`exclude`,		Time=[ 2017-12-15 14:09:34.091000, 2017-12-15 14:09:34.347000]
>> id=0050: label=`tap_hand`,		Time=[ 2017-12-15 14:13:27.040000, 2017-12-15 14:13:27.339000]
>> id=0100: label=`hand_cleaner`,		Time=[ 2017-12-15 14:23:33.897000, 2017-12-15 14:23:35.113000]
>> Success: df.shape= (1011260, 6)

Step3: Write CSV files.
>> Success: Write csv.[ /root/upconversion/data/2017_12_15/03_yasuda/data/Labeled/acc_labeled.csv ]
>> Success: Write csv.[ /root/upconversion/data/2017_12_15/03_yasuda/data/Labeled/labele.csv ]

                     time     x     y     z label  label_id
0 2017-12-15 14:09:15.506 -3824 -8941  2928  none        -1
1 2017-12-15 14:09:15.507 -3812 -8967  2933  none        -1
2 2017-12-15 14:09:15.508 -3797 -8953  2974  none        -1
3 2017-12-15 14:09:15.509 -3792 -8916  2957  none        -1
4 2017-12-15 14:09:15.510 -3795 -8904  2937  none        -1
5 2017-12-15 14:09:15.511 -3758 -8921  2903  none        -1
6 2017-12-15 14:09:15.512 -3760 -8928  2889  none        -1
7 2017-12-15 14:09:15.513 -3734 -8933  2889  none        -1
8 2017-12-15 14:09:15.514 -3699 -8921  2886  none        -1
9 2017-12-15 14:09:15.515 -3707 -8894  2879  none        -1

>>  04_kamiya
Step1: Read csv files and label xml data.
>> /root/upconversion/data/2017_12_15/04_kamiya/data/acc2/acc2_R
>> /root/upconversion/data/2017_12_15/04_kamiya/data/acc2/acc2_R/20171215_150200_acc2.csv
>> /root/upconversion/data/2017_12_15/04_kamiya/data/acc2/acc2_R/20171215_151100_acc2.csv
>> /root/upconversion/data/2017_12_15/04_kamiya/data/acc2/acc2_R/20171215_150700_acc2.csv
>> /root/upconversion/data/2017_12_15/04_kamiya/data/acc2/acc2_R/20171215_145500_acc2.csv
>> /root/upconversion/data/2017_12_15/04_kamiya/data/acc2/acc2_R/20171215_145900_acc2.csv
>> /root/upconversion/data/2017_12_15/04_kamiya/data/acc2/acc2_R/20171215_150900_acc2.csv
>> /root/upconversion/data/2017_12_15/04_kamiya/data/acc2/acc2_R/20171215_151000_acc2.csv
>> /root/upconversion/data/2017_12_15/04_kamiya/data/acc2/acc2_R/20171215_150300_acc2.csv
>> /root/upconversion/data/2017_12_15/04_kamiya/data/acc2/acc2_R/20171215_150600_acc2.csv
>> /root/upconversion/data/2017_12_15/04_kamiya/data/acc2/acc2_R/20171215_145400_acc2.csv
>> /root/upconversion/data/2017_12_15/04_kamiya/data/acc2/acc2_R/20171215_150800_acc2.csv
>> /root/upconversion/data/2017_12_15/04_kamiya/data/acc2/acc2_R/20171215_145800_acc2.csv
>> /root/upconversion/data/2017_12_15/04_kamiya/data/acc2/acc2_R/20171215_145600_acc2.csv
>> /root/upconversion/data/2017_12_15/04_kamiya/data/acc2/acc2_R/20171215_150100_acc2.csv
>> /root/upconversion/data/2017_12_15/04_kamiya/data/acc2/acc2_R/20171215_145700_acc2.csv
>> /root/upconversion/data/2017_12_15/04_kamiya/data/acc2/acc2_R/20171215_150500_acc2.csv
>> /root/upconversion/data/2017_12_15/04_kamiya/data/acc2/acc2_R/20171215_150000_acc2.csv
>> /root/upconversion/data/2017_12_15/04_kamiya/data/acc2/acc2_R/20171215_151200_acc2.csv
>> /root/upconversion/data/2017_12_15/04_kamiya/data/acc2/acc2_R/20171215_150400_acc2.csv
[BFS] fix timestamp =  True
>> Success: df=(1067590, 4), df_label=(120, 3)

Step2: Add label to sensor data.
>> id=0000: label=`exclude`,		Time=[ 2017-12-15 14:54:38.916000, 2017-12-15 14:54:39.068000]
>> id=0050: label=`flick_left`,		Time=[ 2017-12-15 14:58:18.988000, 2017-12-15 14:58:19.300000]
>> id=0100: label=`massarger_slow`,		Time=[ 2017-12-15 15:09:12.575000, 2017-12-15 15:09:15.145000]
>> Success: df.shape= (1067590, 6)

Step3: Write CSV files.
>> Success: Write csv.[ /root/upconversion/data/2017_12_15/04_kamiya/data/Labeled/acc_labeled.csv ]
>> Success: Write csv.[ /root/upconversion/data/2017_12_15/04_kamiya/data/Labeled/labele.csv ]

                     time    x    y      z label  label_id
0 2017-12-15 14:54:28.346  523 -131  10122  none        -1
1 2017-12-15 14:54:28.347  557 -188  10149  none        -1
2 2017-12-15 14:54:28.348  531 -215  10140  none        -1
3 2017-12-15 14:54:28.349  435 -128  10132  none        -1
4 2017-12-15 14:54:28.350  365  -79  10113  none        -1
5 2017-12-15 14:54:28.351  387 -123  10159  none        -1
6 2017-12-15 14:54:28.352  404 -176  10203  none        -1
7 2017-12-15 14:54:28.353  457 -205  10198  none        -1
8 2017-12-15 14:54:28.354  470 -200  10184  none        -1
9 2017-12-15 14:54:28.355  433 -193  10149  none        -1

>>  05_ishiyama
Step1: Read csv files and label xml data.
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_160100_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_154100_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_154800_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_154400_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_155000_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_160200_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_155500_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_154700_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_154500_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_155400_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_154600_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_154000_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_155600_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_155200_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_155300_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_154900_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_160000_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_155100_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_154300_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_155700_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_154200_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_153900_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_155900_acc2.csv
>> /root/upconversion/data/2017_12_15/05_ishiyama/data/acc2/acc2_R/20171215_155800_acc2.csv
[BFS] fix timestamp =  True
>> Success: df=(1425609, 4), df_label=(120, 3)

Step2: Add label to sensor data.
>> id=0000: label=`start_gesture_session`,		Time=[ 2017-12-15 15:39:16.080000, 2017-12-15 15:39:19.120000]
>> id=0050: label=`air_trap`,		Time=[ 2017-12-15 15:46:13.234000, 2017-12-15 15:46:13.633000]
>> id=0100: label=`drill`,		Time=[ 2017-12-15 15:59:16.345000, 2017-12-15 15:59:19.476000]
>> Success: df.shape= (1425609, 6)

Step3: Write CSV files.
>> Success: Write csv.[ /root/upconversion/data/2017_12_15/05_ishiyama/data/Labeled/acc_labeled.csv ]
>> Success: Write csv.[ /root/upconversion/data/2017_12_15/05_ishiyama/data/Labeled/labele.csv ]

                     time     x     y     z label  label_id
0 2017-12-15 15:39:06.726 -2952  1515  9607  none        -1
1 2017-12-15 15:39:06.727 -3001  1554  9602  none        -1
2 2017-12-15 15:39:06.728 -3033  1569  9590  none        -1
3 2017-12-15 15:39:06.729 -3035  1542  9598  none        -1
4 2017-12-15 15:39:06.730 -3033  1510  9544  none        -1
5 2017-12-15 15:39:06.731 -3018  1498  9541  none        -1
6 2017-12-15 15:39:06.732 -2979  1481  9649  none        -1
7 2017-12-15 15:39:06.733 -2962  1486  9659  none        -1
8 2017-12-15 15:39:06.734 -2964  1495  9624  none        -1
9 2017-12-15 15:39:06.735 -2994  1515  9661  none        -1

>>  06_yoshimura
Step1: Read csv files and label xml data.
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R/20171215_165200_acc2.csv
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R/20171215_165300_acc2.csv
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R/20171215_170500_acc2.csv
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R/20171215_165100_acc2.csv
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R/20171215_165400_acc2.csv
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R/20171215_165800_acc2.csv
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R/20171215_170300_acc2.csv
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R/20171215_165000_acc2.csv
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R/20171215_170400_acc2.csv
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R/20171215_164800_acc2.csv
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R/20171215_165700_acc2.csv
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R/20171215_170000_acc2.csv
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R/20171215_170100_acc2.csv
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R/20171215_170600_acc2.csv
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R/20171215_165500_acc2.csv
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R/20171215_164700_acc2.csv
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R/20171215_170200_acc2.csv
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R/20171215_164900_acc2.csv
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R/20171215_165600_acc2.csv
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R/20171215_165900_acc2.csv
>> /root/upconversion/data/2017_12_15/06_yoshimura/data/acc2/acc2_R/20171215_164600_acc2.csv
[BFS] fix timestamp =  True
>> Success: df=(1214760, 4), df_label=(116, 3)

Step2: Add label to sensor data.
>> id=0000: label=`exclude`,		Time=[ 2017-12-15 16:46:15.480000, 2017-12-15 16:46:16.840000]
>> id=0050: label=`pinch_out`,		Time=[ 2017-12-15 16:49:52.333000, 2017-12-15 16:49:52.717000]
>> id=0100: label=`blender`,		Time=[ 2017-12-15 17:03:36.851000, 2017-12-15 17:03:38.668000]
>> Success: df.shape= (1214760, 6)

Step3: Write CSV files.
>> Success: Write csv.[ /root/upconversion/data/2017_12_15/06_yoshimura/data/Labeled/acc_labeled.csv ]
>> Success: Write csv.[ /root/upconversion/data/2017_12_15/06_yoshimura/data/Labeled/labele.csv ]

                     time     x     y     z label  label_id
0 2017-12-15 16:46:10.496 -6263  3434  6888  none        -1
1 2017-12-15 16:46:10.497 -6224  3419  6912  none        -1
2 2017-12-15 16:46:10.498 -6238  3417  6922  none        -1
3 2017-12-15 16:46:10.499 -6256  3417  6893  none        -1
4 2017-12-15 16:46:10.500 -6229  3422  6895  none        -1
5 2017-12-15 16:46:10.501 -6216  3453  6954  none        -1
6 2017-12-15 16:46:10.502 -6229  3463  6963  none        -1
7 2017-12-15 16:46:10.503 -6207  3463  6907  none        -1
8 2017-12-15 16:46:10.504 -6194  3473  6878  none        -1
9 2017-12-15 16:46:10.505 -6187  3471  6866  none        -1

>>  07_aiko
Step1: Read csv files and label xml data.
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_173600_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_174400_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_175000_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_174900_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_173700_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_174100_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_173400_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_173800_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_174700_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_175100_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_174200_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_174600_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_174000_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_175300_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_173900_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_175700_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_175200_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_175400_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_174500_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_173300_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_175600_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_175900_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_175800_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_173500_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_174800_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_174300_acc2.csv
>> /root/upconversion/data/2017_12_15/07_aiko/data/acc2/acc2_R/20171215_175500_acc2.csv
[BFS] fix timestamp =  True
>> Success: df=(1605790, 4), df_label=(115, 3)

Step2: Add label to sensor data.
>> id=0000: label=`start_gesture_session`,		Time=[ 2017-12-15 17:33:22.551000, 2017-12-15 17:33:24.046000]
>> id=0050: label=`pinch_out`,		Time=[ 2017-12-15 17:38:27.008000, 2017-12-15 17:38:27.205000]
>> id=0100: label=`blender`,		Time=[ 2017-12-15 17:55:08.661000, 2017-12-15 17:55:12.205000]
>> Success: df.shape= (1605790, 6)

Step3: Write CSV files.
>> Success: Write csv.[ /root/upconversion/data/2017_12_15/07_aiko/data/Labeled/acc_labeled.csv ]
>> Success: Write csv.[ /root/upconversion/data/2017_12_15/07_aiko/data/Labeled/labele.csv ]

                     time    x    y     z label  label_id
0 2017-12-15 17:33:07.211  467 -867  9827  none        -1
1 2017-12-15 17:33:07.212  487 -889  9871  none        -1
2 2017-12-15 17:33:07.213  448 -894  9873  none        -1
3 2017-12-15 17:33:07.214  426 -886  9820  none        -1
4 2017-12-15 17:33:07.215  457 -911  9800  none        -1
5 2017-12-15 17:33:07.216  435 -916  9805  none        -1
6 2017-12-15 17:33:07.217  433 -940  9847  none        -1
7 2017-12-15 17:33:07.218  428 -933  9859  none        -1
8 2017-12-15 17:33:07.219  445 -957  9834  none        -1
9 2017-12-15 17:33:07.220  499 -982  9805  none        -1

>>  08_higashide
Step1: Read csv files and label xml data.
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_183100_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_182500_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_182200_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_183000_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_182400_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_184000_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_183600_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_183800_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_183200_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_181800_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_183500_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_182900_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_182800_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_182000_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_182600_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_183900_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_182100_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_181900_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_183400_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_182700_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_182300_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_183700_acc2.csv
>> /root/upconversion/data/2017_12_15/08_higashide/data/acc2/acc2_R/20171215_183300_acc2.csv
[BFS] fix timestamp =  True
>> Success: df=(1324650, 4), df_label=(116, 3)

Step2: Add label to sensor data.
>> id=0000: label=`start_gesture_session`,		Time=[ 2017-12-15 18:18:32.979000, 2017-12-15 18:18:34.737000]
>> id=0050: label=`pinch_out`,		Time=[ 2017-12-15 18:23:14.248000, 2017-12-15 18:23:14.626000]
>> id=0100: label=`drill`,		Time=[ 2017-12-15 18:37:22.621000, 2017-12-15 18:37:27.003000]
>> Success: df.shape= (1324650, 6)

Step3: Write CSV files.
>> Success: Write csv.[ /root/upconversion/data/2017_12_15/08_higashide/data/Labeled/acc_labeled.csv ]
>> Success: Write csv.[ /root/upconversion/data/2017_12_15/08_higashide/data/Labeled/labele.csv ]

                     time    x     y      z label  label_id
0 2017-12-15 18:18:27.731  116 -1038  10193  none        -1
1 2017-12-15 18:18:27.732   65 -1026  10208  none        -1
2 2017-12-15 18:18:27.733   14  -974  10242  none        -1
3 2017-12-15 18:18:27.734   -3  -972  10262  none        -1
4 2017-12-15 18:18:27.735   12  -991  10289  none        -1
5 2017-12-15 18:18:27.736   -1  -967  10245  none        -1
6 2017-12-15 18:18:27.737  -54  -935  10245  none        -1
7 2017-12-15 18:18:27.738  -89  -940  10286  none        -1
8 2017-12-15 18:18:27.739  -89  -996  10269  none        -1
9 2017-12-15 18:18:27.740  -71 -1028  10227  none        -1